// Package resources - This file is automatically generated.
// Do not edit this file manually.
// Check `/generator/resources.go` to change generated content
package resources

//ErrorCouldNotSerializeJSON -
var ErrorCouldNotSerializeJSON = "Could not serialize json for video: %s\n"

//ErrorCouldNotRecogniseURL -
var ErrorCouldNotRecogniseURL = "Could not recognise URL format of string %s"

//Error -
var Error = "Error : %s\n"

//ErrorPathNotFound -
var ErrorPathNotFound = "File path %s not found."

//FailedOnItem -
var FailedOnItem = "Failed while scraping item: %s\n"

//FailedToLoadScraper -
var FailedToLoadScraper = "Failed to load scraper"
