// Package resources - This file is automatically generated.
// Do not edit this file manually.
// Check `/generator/resources.go` to change generated content
package resources

//PreloadingItemsFound -
var PreloadingItemsFound = "\rPreloading... %s items have been found."

//Preloading -
var Preloading = "\rPreloading..."

//Retrieving -
var Retrieving = "\nRetrieving items..."

//ItemsFoundInArchive -
var ItemsFoundInArchive = "%d items, found in archive. Skipping...\n"

//Downloaded -
var Downloaded = "\r[%d/%d] Downloaded"

//UsageLine -
var UsageLine = "Usage: tiktok-dl [OPTIONS] TIKTOK_USERNAME|TIKTOK_URL\n  or:  tiktok-dl [OPTIONS] -batch-file path/to/users.txt\n  or:  tiktok-dl [OPTIONS] -scraped-data path/to/data.json"
